name: Angeli Tatum
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59947
title: Angelitatum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe1ae'
    - '#1a1516'
    - '#caab98'
    - '#9d7244'
    - '#69472b'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
