name: Angeli Tatum
favicon: null
layout_spectrum: 0.88635
typography_spectrum: 0.59947
title: Angelitatum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#093687'
    - '#843d81'
    - '#ed5659'
    - '#feae86'
    - '#fef748'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
