name: Angeli Tatum
favicon: null
layout_spectrum: 0.8823562802281231
typography_spectrum: 0.3387156664393842
title: Angelitatum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5779079168569297
  lightness: 0.990217850310728
  saturation: 0.15621052030473948
  rhythmicContrast: 0.5958724436350167
purpose: []
