name: Angeli Tatum
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55497
title: Angelitatum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#b5bdb6'
    - '#f4f0ef'
    - '#c2142b'
    - '#00d7ea'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
